### ISSUE TITLE
Null check operator used on a null value  The relevant error-causing widget was GetBuilder<CheckOutViewModel> ??

### ISSUE THREAD

**Issue by EsraaHelaly** [UsamaElgendy/status_change#1]

**Comment by SittiphanSittisak** [comment]
Same (Null check operator used on a null value)
Can someone give minimal code like:

Container(
     width: 100.0,
     height: 50.0,
     StatusChange(
          direction: vertical,
          bg: Colors.white,
          child:[
                    status 1(
                         display: controller == 1 ? true : false,
                         color = Colors.red,
                    ),
                    status 2(
                         display: controller == 2 ? true : false,
                         color = Colors.red,
                    ),
                    status 3(
                         display: controller ==3 ? true : false,
                         color = Colors.red,
                    ),
                     
               ]
     )
)

Thank you.

**Comment by muhammadkamel** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      StatusChangeTileBuilder._createConnectedStartConnectorBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:89:20)

**Comment by NasSatellite** [comment]
> ════════ Exception caught by widgets library ═══════════════════════════════════
> The following _CastError was thrown building:
> Null check operator used on a null value
> 
> When the exception was thrown, this was the stack
> #0 StatusChangeTileBuilder._createConnectedStartConnectorBuilder. (package:status_change/src/component/status_change_tile_builder.dart:89:20)

I have this same issue

**Comment by league-10** [comment]
> > ════════ Exception caught by widgets library ═══════════════════════════════════
> > The following _CastError was thrown building:
> > Null check operator used on a null value
> > When the exception was thrown, this was the stack
> > #0 StatusChangeTileBuilder._createConnectedStartConnectorBuilder. (package:status_change/src/component/status_change_tile_builder.dart:89:20)
> 
> I have this same issue

1.0.0 Try this Version

**Comment by league-10** [comment]
2.0.0 coming with null safety

**Comment by madsamarty** [comment]
Check the fix in pull requests
