### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by pratikgtam** [UsamaElgendy/status_change#2]
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      StatusChangeTileBuilder._createConnectedStartConnectorBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:89:20)
#1      new StatusChangeTileBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:56:52)
#2      StatusChangeTileBuilder.build (package:status_change/src/component/status_change_tile_builder.dart:81:20)
#3      SliverChildBuilderDelegate.build
#4      SliverMultiBoxAdaptorElement._build
...
════════════════════════════════════════════════════════════════════════════════
W/IInputConnectionWrapper(21429): getExtractedText on inactive InputConnection

**Comment by hamodass** [comment]
Change Package Version to ^1.0.0

**Comment by sopharasum** [comment]
> ════════ Exception caught by widgets library ═══════════════════════════════════
> The following _CastError was thrown building:
> Null check operator used on a null value
> 
> When the exception was thrown, this was the stack
> #0 StatusChangeTileBuilder._createConnectedStartConnectorBuilder. (package:status_change/src/component/status_change_tile_builder.dart:89:20)
> #1 new StatusChangeTileBuilder. (package:status_change/src/component/status_change_tile_builder.dart:56:52)
> #2 StatusChangeTileBuilder.build (package:status_change/src/component/status_change_tile_builder.dart:81:20)
> #3 SliverChildBuilderDelegate.build
> #4 SliverMultiBoxAdaptorElement._build
> ...
> ════════════════════════════════════════════════════════════════════════════════
> W/IInputConnectionWrapper(21429): getExtractedText on inactive InputConnection

@hamodass when is this issue gonna fixed on Flutter 2.0 null safety?

**Comment by ikmazameti** [comment]
I experienced the same issues.

**Comment by madsamarty** [comment]
Check the fix in pull requests

**Comment by sopharasum** [comment]
Hope it is going to merge very soon

**Comment by usamaaelgendy** [comment]
👍
