### ISSUE TITLE
Null Check Operator used on a null value issue 

### ISSUE THREAD

**Issue by laxkarparas1** [UsamaElgendy/status_change#5]
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      StatusChangeTileBuilder._createConnectedStartConnectorBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:89:20)
#1      new StatusChangeTileBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:56:52)
#2      StatusChangeTileBuilder.build (package:status_change/src/component/status_change_tile_builder.dart:81:20)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:457:22)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1215:28)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:55)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#38     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#42     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#43     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#44     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#48     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#50     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#51     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#52     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#54     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:504:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#71     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#75     RenderSliverToBoxAdapter.performLayout (package:flutter/src/rendering/sliver.dart:1809:12)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#77     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#78     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#79     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#96     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#100    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#101    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#102    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#104    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#106    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#107    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#108    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#110    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#111    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#112    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#113    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#116    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#118    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#122    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#123    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#125    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#126    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#127    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#128    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#130    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#133    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#135    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#137    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#139    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#140    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#141    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#142    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3426:14)
#143    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#145    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#146    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#147    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#148    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#149    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#150    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#151    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#152    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#153    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#154    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#158    _invoke (dart:ui/hooks.dart:150:10)
#159    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#160    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)

**Comment by laxkarparas1** [comment]
to fix this issue you have to copy StatusChangeTileBuilder code from git example and paste it to your package StatusChangeTileBuilder file in your project

**Comment by iamafzalhassan** [comment]
> to fix this issue you have to copy StatusChangeTileBuilder code from git example and paste it to your package StatusChangeTileBuilder file in your project

Bro I didn't get it, could you please explain it a bit further?
