### ISSUE TITLE
Null Check operator used on a null value???

### ISSUE THREAD

**Issue by Hatrick19** [UsamaElgendy/status_change#6]
![WhatsApp Image 2022-02-05 at 5 56 12 PM](https://user-images.githubusercontent.com/81321999/152649365-a545663b-931f-4821-ace1-392c9dde0bca.jpeg)

**Comment by Hatrick19** [comment]
import 'package:alan/constants.dart';
import 'package:alan/screens/checkout/components/add_address.dart';
import 'package:alan/screens/checkout/components/delevery_time.dart';
import 'package:alan/screens/checkout/components/summary.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:status_change/status_change.dart';

class CheckOutView extends StatefulWidget {
  static String routeName = "/checkout";
  const CheckOutView({Key? key}) : super(key: key);

  @override
  _CheckOutViewState createState() => _CheckOutViewState();
}

class _CheckOutViewState extends State<CheckOutView> {
  int _processIndex = 0;
  Pages pages = Pages.DeliveryTime;

  Color getColor(int index) {
    if (index == _processIndex) {
      return inProgressColor;
    } else if (index < _processIndex) {
      return Colors.green;
    } else {
      return todoColor;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0.0,
        title: const Text(
          "Order Status",
          style: TextStyle(
            color: Colors.black,
          ),
        ),
      ),
      backgroundColor: Colors.white,
      body: Column(
        children: [
          Expanded(
            child: StatusChange.tileBuilder(
              theme: StatusChangeThemeData(
                direction: Axis.vertical,
                connectorTheme:
                    const ConnectorThemeData(space: 1.0, thickness: 1.0),
              ),
              builder: StatusChangeTileBuilder.connected(
                itemWidth: (_) =>
                    MediaQuery.of(context).size.width / _processes.length,
                contentWidgetBuilder: (context, index) {
                  return const Padding(
                    padding: EdgeInsets.all(15.0),
                    child: Text(
                      'add content here',
                      style: TextStyle(
                        color: Colors
                            .blue, // change color with dynamic color --> can find it with example section
                      ),
                    ),
                  );
                },
                nameWidgetBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.all(20),
                    child: Text(
                      'your text ',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        color: getColor(index),
                      ),
                    ),
                  );
                },
                indicatorWidgetBuilder: (_, index) {
                  if (index <= _processIndex) {
                    return DotIndicator(
                      size: 35.0,
                      border: Border.all(color: Colors.green, width: 1),
                      child: Padding(
                        padding: const EdgeInsets.all(6.0),
                        child: Container(
                          decoration: const BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.green,
                          ),
                        ),
                      ),
                    );
                  } else {
                    return const OutlinedDotIndicator(
                      size: 30,
                      borderWidth: 1.0,
                      color: todoColor,
                    );
                  }
                },
                lineWidgetBuilder: (index) {
                  if (index > 0) {
                    if (index == _processIndex) {
                      final prevColor = getColor(index - 1);
                      final color = getColor(index);
                      var gradientColors;
                      gradientColors = [
                        prevColor,
                        Color.lerp(prevColor, color, 0.5)
                      ];
                      return DecoratedLineConnector(
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: gradientColors,
                          ),
                        ),
                      );
                    } else {
                      return SolidLineConnector(
                        color: getColor(index),
                      );
                    }
                  } else {
                    return null;
                  }
                },
                itemCount: _processes.length,
              ),
            ),
          ),
          pages == Pages.DeliveryTime
              ? const DeliveryTime()
              : pages == Pages.AddAddress
                  ? const AddAddress()
                  : const Summ()
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.skip_next),
        onPressed: () {
          if (kDebugMode) {
            print(_processIndex);
          }
          setState(() {
            _processIndex++;
            if (_processIndex == 1) {
              pages = Pages.AddAddress;
            } else if (_processIndex == 2) {
              pages = Pages.Summ;
            } else if (_processIndex == 3) {}
          });
        },
        backgroundColor: inProgressColor,
      ),
    );
  }
}

final _processes = [
  'Order Signed',
  'Order Processed',
  'Shipped ',
  'Out for delivery ',
  'Delivered ',
];

final _content = [
  '20/18',
  '20/18',
  '20/18',
  '20/18',
  '20/18',
];

**Comment by Hatrick19** [comment]
Any help in this matter..?

**Comment by splex7** [comment]
Same issue.

**Comment by Pusse-01** [comment]
I also face the same issue. Any answer for this?

**Comment by sepehr13494** [comment]
same issue

**Comment by bimalnair** [comment]
Same Issue any solution?

**Comment by moh-afifi** [comment]
Same issue. Any Solution?

**Comment by abdalazeez1** [comment]
same issue

**Comment by abdalazeez1** [comment]
[log] Null check operator used on a null value
      #0      StatusChangeTileBuilder._createConnectedStartConnectorBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:89:20)
      #1      new StatusChangeTileBuilder.<anonymous closure> (package:status_change/src/component/status_change_tile_builder.dart:56:52)
      #2      StatusChangeTileBuilder.build (package:status_change/src/component/status_change_tile_builder.dart:81:20)
      #3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:471:22)
      #4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1236:28)
      #5      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1169:67)
      #6      Iterable.forEach (dart:core/iterable.dart:325:35)

**Comment by abuzar-deck** [comment]
same issue

**Comment by Mamun-Lab** [comment]
same issue

**Comment by umidshox99** [comment]
same issuse any solution?

**Comment by kirwako** [comment]
that's happen because you use the package on flutter version >= 2,
and since in flutter >=2 null safety included this problem happen
so the owner of the package need to upgrade the package
are you need to downgrade the version of flutter to version 1

**Comment by akumakhalibagas** [comment]
same issue, please fix this issue for flutter version > 2

**Comment by mizukageyama** [comment]
Same issue

**Comment by kirwako** [comment]
You can fix this issue by just changing `return null!;` to `return Container(child: null);` in status_change package.

**Comment by ahmed-hady-dev** [comment]
> You can fix this issue by just changing `return null!;` to `return Container(child: null);` in status_change package.

That's right and worked for me 👏

and for any one who is going to use the example make sure to modify this 
instead of : 

var gradientColors;
gradientColors = [prevColor,  Color.lerp(prevColor, color, 0.5)]; 

use this :
 
List\<Color> gradientColors;
gradientColors = [prevColor, Color.lerp(prevColor, color, 0.5)!];

**Comment by polarby** [comment]
Programmer: `return null!;`
Flutter introducing null safety: Am I a joke to you?

**Comment by usamaaelgendy** [comment]
Check Now All Fixed 👍
